name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  lint_js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install jshint

      - run: npx jshint giftlink-backend

  client_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build frontend
        working-directory: giftlink-frontend
        run: |
          npm install
          npm run build
          echo "Build successful"
